# Generated by Django 3.2.3 on 2025-07-31 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20250729_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='frontend/src/images/avatar-icon.png', null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
    ]
