from rest_framework import status


HTTP_OK = status.HTTP_200_OK
HTTP_CREATED = status.HTTP_201_CREATED
HTTP_NO_CONTENT = status.HTTP_204_NO_CONTENT
HTTP_BAD_REQUEST = status.HTTP_400_BAD_REQUEST
HTTP_FORBIDDEN = status.HTTP_403_FORBIDDEN
HTTP_NOT_FOUND = status.HTTP_404_NOT_FOUND
HTTP_METHOD_NOT_ALLOWED = status.HTTP_405_METHOD_NOT_ALLOWED

MAX_USERNAME_LENGTH = 150
MAX_EMAIL_LENGTH = 254
MAX_FIRST_NAME_LENGTH = 150
MAX_LAST_NAME_LENGTH = 150
MAX_NAME_LENGTH = 256
MAX_MEASUREMENT_UNIT_LENGTH = 25
MIN_COOKING_TIME = 1
MIN_AMOUNT = 1
MAX_AMOUNT = 10000
MAX_NAME_IMAGE = 50
MAX_UUID_LENGTH = 5

PAGE_SIZE = 6
MAX_PAGE_SIZE = 100

DOMAIN_NAME = 'foodgram.ddnsking.com'
